CONFIG_SPIKE_BUILD_TAG="D-watchdog"
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.4+0"
CONFIG_SPIKE_OTA_AUTO_CONFIRM=n
CONFIG_APP_LIVENESS_SELFTEST=y
CONFIG_APP_LIVENESS_SELFTEST_BLOCK_WQ=y
CONFIG_APP_LIVENESS_SELFTEST_DELAY_S=5
